apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: items-db
  namespace: default
spec:
  instances: 4
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: app
      owner: raoul
