apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headscale-operator-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default

  source:
    repoURL: https://github.com/infradohq/headscale-operator
    targetRevision: v0.6.0
    path: helm/crds

  destination:
    server: https://kubernetes.default.svc
    namespace: headscale-operator

  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
